import React from "react";
import Header from "./Header";
import Footer from "./Footer";
import Head from "next/head";
import { motion, useScroll } from "framer-motion";

const Layout = (props: any) => {
    const { children } = props;
    const { title } = props;
    const { scrollYProgress } = useScroll();

    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <div className="lg:ml-290 xl:ml-320">
                <motion.div className="progress-bar" style={{ scaleX: scrollYProgress }} />
                {children}
                <Footer />
            </div>
        </>
    );
};

export default Layout;
